testPj/myapp/urls.py
from django.urls import path
from . import views

app_name="myapp"

urlpatterns = [
    path("", views.TopView.as_view(), name="top"),
    path("home/", views.HomeView.as_view(), name="home"),
    path("myview/",views.my_view, name="form"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

testPj/testPj/urls.py
from django.urls import path, include

"""
URL configuration for testPj project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('myapp/', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

testPj/myapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="")
    day = models.DateField()

    def __str__(self):
        return self.name

testPj/myapp/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'day']

testPj/myapp/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from . import forms
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserProfileForm
from .models import UserProfile
from django.views.decorators.http import require_http_methods

class TopView(TemplateView):
    template_name = "myapp/top.html"

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "myapp/home.html"

class LoginView(LoginView):
    """ログインページ"""
    form_class = forms.LoginForm
    template_name = "myapp/login.html"

@require_http_methods(['POST'])
def my_view(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            day = form.cleaned_data['day']
            # データベースに保存するためのモデルインスタンスを作成
            my_model = UserProfile(name=name, day=day)
            my_model.save()
            return redirect('home')  # 成功時のリダイレクト先URLを指定
            #return render(request, 'home.html', {'form': form})
    else:
        form = UserProfileForm()
    return render(request, 'home.html', {'form': form})

'''
@require_http_methods(['POST'])
@login_required(login_url='login')  # ログインが必要な場合はこのデコレータを追加します
def my_view(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            day = form.cleaned_data['day']
            # データベースに保存するためのモデルインスタンスを作成
            my_model = UserProfile(name=name, day=day)
            my_model.save()
            return redirect('home')  # 成功時のリダイレクト先URLを指定
    else:
        form = UserProfileForm()
    return render(request, 'home.html', {'form': form})
'''

class LogoutView(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = "myapp/login.html"

testPj/templates/myapp/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    {% block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

testPj/templates/myapp/form.html
{% extends "myapp/base.html" %}

{% block title %}フォーム{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <!-- 名前の入力フォーム -->
    <input type="text" name="name" required>
    <!-- 日にちの入力フォーム -->
    <input type="date" name="date" required>
    <!-- 送信ボタン -->
    <button type="submit">保存</button>
</form>

{% endblock %}

testPj/templates/myapp/home.html
{% extends "myapp/base.html" %}
{% block title %}ホーム{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5"></h1>
    <p>{{ user.username }}さん、こんにちは。</p>

    <a href="{% url 'myapp:logout' %}">ログアウト</a>
</div>
{% endblock %}

testPj/templates/myapp/login.html
{% extends "myapp/base.html" %}
{% block title %}ログイン{% endblock %}

{% block content %}
<div class="container">
    <h1>ログイン</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            {{ field.label }}
            <br>
            {{ field }}
            <br>
            {{ field.error }}
        {% endfor %}
        <br>
        <button type="submit">ログイン</button>
    </form>
</div>
{% endblock %}

testPj/templates/myapp/top.html
{% extends "myapp/base.html" %}

{% block title %}トップ{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">Top画面</h1>
    <a href="{% url 'myapp:login' %}" class="btn btn-outline-primary">ログイン</a>
</div>
{% endblock %}